### PR TITLE
Add Rocky Linux 9 client support documentation (#1661)

### LINKED ISSUE #1661: Add Rocky Linux 9 Documentation
Complete as much information as possible.
Replace the description text with your response.

## Documentation Update Required

As mentioned in [uyuni#5682](https://github.com/uyuni-project/uyuni/pull/5682) it is needed to add documentation for Rocky Linux 9.

## What does the documentation say now?

It only mentions version 8, but not 9 up to now.

## What change is required?

It is most likely nearly the same documentation that's needed, there are no module streams up to now, but they will most likely come with 9.1 so it's really the same documentation as for 8.

## Version

Which version of the software is this feature/update expected to land in (if known)?
Which version of the documentation must this feature/update land in (if known)?
Does the content need to be backported to previous documentation versions (if known)?

I think `2022.07` or `2022.08`, it's a new feature so no backporting needed.

Thank you very much!
If needed I can also update the docs myself and send a PR 👍🏻

### PR DESCRIPTION
**Pull request by lumarel**
# Description

**~Blocked until https://github.com/uyuni-project/uyuni/pull/5682 is merged.~** [merged]

This PR documents the upcoming support for Rocky Linux 9, it should be in with version 2022.08 if I understood that correctly.

A few notes:

- it mentions that ppc64le and s390x is supported, this will be needed to be removed if the venv doesn't get built for these platforms
- it also removes ppc64le support from Rocky Linux 8, as this arch never took off in the project for 8
- I did not adjust the support tables for SUSE Manager, because I don't have insight in the SUSE internas

Beside that, Rocky Linux 9 is pretty much the same story as 8 in Uyuni, the only difference is, that there will not be a normal build for the salt-minion only a venv-salt-minion, but I don't think this needs to be promoted on the individual registration page as this is a overall topic, where as far as I understood it all clients will be moved to venv only.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #1661

### CODE REVIEW

**Review by keichwa — APPROVED** [review]
Thanks, looks good!

**Comment by keichwa** [comment]
@juliogonzalez can you take a quick look?

**Comment by keichwa** [comment]
We need someone who can check the SUMA tables (see description).  Because of the ppc64le remark, we probably should fix the 4.3 and 4.2 documentation accordingly.

**Review by juliogonzalez — COMMENTED** [review]
@keichwa, yes: removing ppc64le for Rocky Linux 8 is needed. Only Rocky Linux 9 has it. Make sure it's backported to 4.3 and 4.2.

This whole PR will need to be backported to 4.3 as well, but not yet (only when we add Rocky Linux 0 support for SUSE Manager 4.3).

I recommend you generate the doc and reviewit before merging this PR.

**Comment by juliogonzalez** [comment]
@keichwa before merging this, please keep in mind https://github.com/SUSE/spacewalk/issues/18472, as we need the PR for the code merged, and it's not merged yet. We still didn't release 2022.08

**Review by jcayouette — APPROVED** [review]

**Comment by keichwa** [comment]
> @keichwa before merging this, please keep in mind [SUSE/spacewalk#18472](https://github.com/SUSE/spacewalk/issues/18472), as we need the PR for the code merged, and it's not merged yet. We still didn't release 2022.08

Can you

> @keichwa before merging this, please keep in mind [SUSE/spacewalk#18472](https://github.com/SUSE/spacewalk/issues/18472), as we need the PR for the code merged, and it's not merged yet. We still didn't release 2022.08

Ok, I think this is the code PR we depend on: https://github.com/uyuni-project/uyuni/pull/5682

**Comment by lumarel** [comment]
@keichwa Thank you for taking the time!
the PR should be merged now 🙂

**Comment by lumarel** [comment]
Fixed that merge conflict 👍

**Pull request merged**
