### PR TITLE
Add SLE Micro to supported features table

### PR DESCRIPTION
**Pull request by moio**
# Description

Add SLE Micro to the supported features table (I noticed it was missing too late).

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

### CODE REVIEW

**Review by jcayouette — APPROVED** [review]
LGTM, Thanks! See update below. Saw the error a bit late.

**Review by jcayouette — CHANGES_REQUESTED** [review]
We already have a macro for SLE Micro however so we should probably use this one:

```micro: 'SLE Micro'```

{micro}

**Comment by moio** [comment]
> We already have a macro for SLE Micro so we should probably use this one:
> In our _suma-site.yml_, _uyuni-site.yml_, and _entities.pdf_ we have:
> 
> `micro: 'SLE Micro'`
> 
> So we should use the following:
> 
> ```
> | {micro}
> ```

fixed, thanks

**Review by jcayouette — APPROVED** [review]

**Comment by moio** [comment]
picked to `manager-4.2` as well

**Pull request merged**
