### PR TITLE
update 4.1 screenshots

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Short summary of why you created this PR

# Target branches

To what product version this document applies?

- [ ] Manager-3.2
- [ ] Manager-4.0
- [x] Manager-4.1
- [ ] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/11657

### CODE REVIEW

**Comment by keichwa** [comment]
On 2020-06-10 21:10, Ondřej Holeček wrote:
> For some installation screenshots feel free to use also our openqa
> instances, i.e. http://sleposbuilder4.suse.cz/tests/28752 for
> installation job.

Thank you Ondřej, this is a nice offering!  We also want this for 
regular
suma installs ;)

> We are in a process of updating our required checkpoing screenshots
> with new SUMA branding, once that is ready, we'll be able to provide
> some generic usage screenshots as well.

I surely want to learn more about openqa!

-- 
Karl Eichwalder                    SUSE Software Solutions Germany GmbH
                                    Maxfeldstraße 5
                                    90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by keichwa** [comment]
I think these are the screenshots of the installation procedures (yast): manager, retail server, and proxy.  i'll check the web ui screens separately.

**Comment by Loquacity** [comment]
> I think these are the screenshots of the installation procedures (yast): manager, retail server, and proxy. i'll check the web ui screens separately.

Do you have an issue for this?

**Comment by keichwa** [comment]
I'll work on it as part of https://github.com/SUSE/spacewalk/issues/11657

**Pull request merged**
