### PR TITLE
Patch fix for several issues in nav lists, NBSP macros, and missing adoc extensions

### PR DESCRIPTION
**Pull request by jcayouette**
# Description
This patch addresses some rather severe issues that came up. We missed a few nav list issues specifically missing **.adoc** extension on the end of several files. There were also a few NBSP macros that were corrupted and breaking tables across books. This brings everything back into a clean build status.

The large number of files is due to regeneration of POT files for translation. Otherwise simple fixes.

Short summary of why you created this PR
Build was broken at master.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [X] Manager-4.1
- [X] Manager-4.2
- [X] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by jcayouette** [comment]
I will use superpowers to merge. This needs to be fixed asap.

**Comment by keichwa** [comment]
Thanks for fixing it!

**Comment by paususe** [comment]
@jcayouette 

I'm afraid this PR is wrong and will need to be reverted. The Spanish-translated strings have been replaced with empty strings.

How did you generate this?

**Comment by Loquacity** [comment]
I think this is what has stomped all over master, too.

**Pull request merged**
