### PR TITLE
Branding update 2021

### PR DESCRIPTION
**Pull request by jcayouette**
# Description

Branding update for 2021.

Font updated to poppins. This PR covers HTML for D.S.C and the webui. It does not cover PDF changes.

# Target branches

Which documentation version does this PR apply to?

- [X] Master (Default)
- [X] Manager-4.1
- [X] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by keichwa — APPROVED** [review]
Un-reviewable ;) 1680 files changed.  But I saw the screenshots you posted.  Thus approved! :-)

**Comment by Loquacity** [comment]
Do we really want to backport this all the way back?

**Comment by keichwa** [comment]
> Do we really want to backport this all the way back?

This is a very valid question.  In the past, I also thought backporting layout or branding changes is wrong (my argument is: do not change history!).  But people seem to think different, and thus I stopped vetoing ;) iirc, they do not want to maintain two or more tool collections.

**Comment by Loquacity** [comment]
> > Do we really want to backport this all the way back?
> 
> This is a very valid question. In the past, I also thought backporting layout or branding changes is wrong (my argument is: do not change history!). But people seem to think different, and thus I stopped vetoing ;) iirc, they do not want to maintain two or more tool collections.

Yes, and I guess there's an argument for having all versions look the same, too. I don't mind terribly either way, just trying to limit how many backports we do.

**Comment by jcayouette** [comment]
Aye, I agree back-porting everything is not bp. However I feel like branding is the company image and if our docs are not consistent across the board is displays a lack of professionalism, and lack of consistency which customers should expect.  More importantly is shows that we are slow at getting changes in. We do not want this image, we want to display our agile capabilities :D

**Comment by Loquacity** [comment]
> Aye, I agree back-porting everything is not bp. However I feel like branding is the company image and if our docs are not consistent across the board is displays a lack of professionalism, and lack of consistency which customers should expect. More importantly is shows that we are slow at getting changes in. We do not want this image, we want to display our agile capabilities :D
> 
> One of the nice features of Antora is that we can make the modifications to the theme (Which are then packaged as a zip, or supplemental directory), then just copy those changes to whatever branch without breaking anything. It is kind of the point for using such a system :D

Fair point! Don't forget the backport, in that case :wink:

**Pull request merged**
