### PR TITLE
BACKPORT 4.1: Rename `hub_server` to `mgr_origin_server` (#797)

### PR DESCRIPTION
**Pull request by Loquacity**
* Rename `hub_server` to `mgr_origin_server`

Rename `hub_server` to `mgr_origin_server` in Salt pillar data

* Update modules/salt/pages/salt-ssh.adoc

Co-authored-by: Lana Brindley <lbrindley@suse.de>

Co-authored-by: Lana Brindley <lbrindley@suse.de>

# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by witekest** [comment]
Looks good. [Backport PR](https://github.com/SUSE/spacewalk/pull/13927) still in review.

**Review by keichwa — APPROVED** [review]
From the suse manager POV, the naming is not that clever ;)

**Comment by witekest** [comment]
> From the suse manager POV, the naming is not that clever ;)

We had a long discussion around naming.
Please compare comments starting from [here](https://github.com/uyuni-project/uyuni/pull/3145#pullrequestreview-573106842)
and [this discussion](https://chat.suse.de/channel/xrhJGnseykFgwLTXA).

**Comment by witekest** [comment]
> Looks good. [Backport PR](https://github.com/SUSE/spacewalk/pull/13927) still in review.

Merged now.

**Comment by keichwa** [comment]
Witek Bedyk <notifications@github.com> writes:

> We had a long discussion around naming.
> Please compare comments starting from
> [here](https://github.com/uyuni-project/uyuni/pull/3145#pullrequestreview-573106842)
> and [this discussion](https://chat.suse.de/channel/xrhJGnseykFgwLTXA).

Thanks you for the additional info!

-- 
Karl Eichwalder

**Pull request merged**
