### PR TITLE
Adds Ubuntu 20.04 to Uyuni

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Adds Ubuntu 20.04 supported features to the Uyuni table.

@juliogonzalez Are you able to check this for us? (or suggest someone who can?)

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [ ] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/uyuni-project/uyuni-docs/issues/476

### CODE REVIEW

**Comment by juliogonzalez** [comment]
Not me, I am not aware of what we support and what not.

I guess the same we support for Ubuntu 20.04, sin the list of packages (that are not dependencies) is basically the same.

Check the release notes for 4.1 and 4.0 and see the announcement Pau added there. There should be information enough to handle this.

**Comment by Shirocco88** [comment]
Please also add "Ubuntu 20.04" to the following docu:
https://www.uyuni-project.org/pages/devel-version.html

**Comment by Loquacity** [comment]
> Please also add "Ubuntu 20.04" to the following devel version docu:
> https://www.uyuni-project.org/pages/devel-version.html
> 

That doc is not maintained by this team, sorry.

**Review by keichwa — APPROVED** [review]
looks clean :)

**Pull request merged**
