### PR TITLE
Fixing the Supported clients table

### PR DESCRIPTION
**Pull request by 0rnela**
Replacing the old table where one column was obsolete, with more detailed one where every architecture is given its separate column.

**OLD**
Screenshot from 2024-02-21 16-24-01

**NEW**
Screenshot from 2024-02-21 16-24-06

### CODE REVIEW

**Comment by blu-base** [comment]
It might make sense to merge the column `x86_64` and `amd64`, wouldn't it? Usually, Debian is labeling itself as `amd64`. However it has been listed as `x86_64` here.

**Comment by 0rnela** [comment]
> It might make sense to merge the column `x86_64` and `amd64`, wouldn't it? Usually, Debian is labeling itself as `amd64`. However it has been listed as `x86_64` here, while Ubuntu is set to 'amd64`.
> 
> Ignore this comment, if this is idea is better discussed separately

@blu-base thank you. I'll bring it up for the discussion with the team.

**Review by jcayouette — APPROVED** [review]
I like it :+1:

**Comment by 0rnela** [comment]
Current tables for for Uyuni:

**OLD**
Screenshot from 2024-02-22 14-54-16
 
**NEW**
Screenshot from 2024-02-22 14-56-01

**Comment by 0rnela** [comment]
Superseded by https://github.com/uyuni-project/uyuni-docs/pull/2823. Closing.

**Pull request closed without merging**
