### PR TITLE
Remove ABRT and the "Software Crashes" feature

### PR DESCRIPTION
**Pull request by ricardoasmarques**
**DO NOT MERGE UNTIL https://github.com/uyuni-project/uyuni/pull/3122 IS MERGED**

---

# Description

PR https://github.com/uyuni-project/uyuni/pull/3122 will remove **ABRT** and the "**Software Crashes**" feature, so we need to update the documentation accordingly.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes: https://github.com/uyuni-project/uyuni/pull/3122
Fixes: https://github.com/SUSE/spacewalk/issues/13075

### CODE REVIEW

**Comment by Loquacity** [comment]
LGTM, but please remove the l10n .cfg  files from this commit.

**Comment by ricardoasmarques** [comment]
> LGTM, but please remove the l10n .cfg files from this commit.

Done, thanks for the hint.

**Review by keichwa — APPROVED** [review]

**Comment by Loquacity** [comment]
@ricardoasmarques Does this need to go into 4.1, or is it 4.2 only?

**Review by Loquacity — APPROVED** [review]

**Comment by ricardoasmarques** [comment]
> @ricardoasmarques Does this need to go into 4.1, or is it 4.2 only?

It's 4.2 only.

**Comment by Loquacity** [comment]
> > @ricardoasmarques Does this need to go into 4.1, or is it 4.2 only?
> 
> It's 4.2 only.

OK, let's merge to master only once the repo is unfrozen, then.

**Comment by Loquacity** [comment]
I see that https://github.com/uyuni-project/uyuni/pull/3122 is merged. @ricardoasmarques are you good for me to merge this one now?

**Review by jcayouette — APPROVED** [review]

**Pull request merged**
