### PR TITLE
for gh-pages

### PR DESCRIPTION
**Pull request by keichwa**
uyuni 2023.10; `en`, `ja`, `ko`, and `zh_CN`.

### CODE REVIEW

**Comment by jcayouette** [comment]
Why is this EN only? All translations should be included.

**Comment by keichwa** [comment]
> Why is this EN only? All translations should be included.

Ok, will try this, too!

**Comment by keichwa** [comment]
> > Why is this EN only? All translations should be included.
> 
> Ok, will try this, too!

Done, pls check again!

**Review by deneb-alpha — APPROVED** [review]
Thanks

**Pull request merged**
