### PR TITLE
Fixes in the Admin Guide / SSL certs

### PR DESCRIPTION
**Pull request by 0rnela**
- [ ]  mgradm restart

https://github.com/SUSE/spacewalk/issues/24285

### CODE REVIEW

**Comment by cbosdo** [comment]
The proxy part will need https://github.com/uyuni-project/uyuni-tools/issues/263 to be updated

**Comment by 0rnela** [comment]
Server part changed.

Awaiting Proxy PR.

**Comment by mbussolotto** [comment]
these are the PR: 
- https://github.com/uyuni-project/uyuni/pull/8779
- https://github.com/uyuni-project/uyuni-tools/pull/320

they add two flags to `mgrprxy [install|upgrade]` command:
```
      --tuning-httpd string       HTTPD tuning configuration file
      --tuning-squid string       Squid tuning configuration file
```

**Review by cbosdo — COMMENTED** [review]
What is already changed looks good, but the proxy part further down the page still needs a change.

You can create a file (for instance `/etc/uyuni/custom-httpd.conf`) with the following line as content. Then you can use `--tuning-httpd /etc/uyuni/custom-httpd.conf` on `mgrpxy install podman` to add the configuration.

```
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains"
```

Note that for now there is no easy way to toggle this after the installation.

**Pull request closed without merging**
