### PR TITLE
"Package locking" on Ubuntu and Debian

### PR DESCRIPTION
**Pull request by keichwa**
# Description

https://github.com/uyuni-project/uyuni-docs/issues/1276
https://github.com/SUSE/spacewalk/issues/16331

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by keichwa** [comment]
I hope I got it right.  If yes, is it supported on 4.2 and 4.1?

**Comment by vzhestkov** [comment]
@keichwa I think it's only about 4.2 and higher, but not for 4.1

**Review by vzhestkov — APPROVED** [review]
Looks good

**Comment by mcalmer** [comment]
@keichwa Victor is correct. Only ported to 4.2 - this feature is not available in 4.1

**Review by mcalmer — APPROVED** [review]

**Comment by keichwa** [comment]
thanks for all your feedback!

**Pull request merged**
