### PR TITLE
Proxy y upgrade spmigration keichwa

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Add proxy SP migration

# Target branches

To what product version this document applies?

- [ ] Manager-3.2
- [ ] Manager-4.0
- [x] Manager-4.1
- [x] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by keichwa** [comment]
ATM, this is just a hort hint.

I prepared it for master (Uyuni), but we probably also want this in 4.1.

**Comment by Loquacity** [comment]
> ATM, this is just a hort hint.
> 
> I prepared it for master (Uyuni), but we probably also want this in 4.1.

Master will go to 4.1 as well.

**Comment by Loquacity** [comment]
Looks like modules/upgrade/assets/images/proxy-spmigration2-0.png still needs cropping.

**Comment by keichwa** [comment]
On 2020-07-02 04:25, Lana Brindley wrote:
> Looks like modules/upgrade/assets/images/proxy-spmigration2-0.png
> still needs cropping.

Yes, but I currently don't use this one.

-- 
Karl Eichwalder                    SUSE Software Solutions Germany GmbH
                                    Maxfeldstraße 5
                                    90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by keichwa** [comment]
I guess I can merge it now.

**Comment by Loquacity** [comment]
> I guess I can merge it now.

Yes, go ahead.

**Pull request merged**
