### PR TITLE
Update containerized server monitoring

### PR DESCRIPTION
**Pull request by witekest**
# Description

Update information about monitoring containerized server.

# Target branches

* Uyuni
* SUMA 5.0

# Links
- This PR tracks issue SUSE/spacewalk#23951

### CODE REVIEW

**Comment by keichwa** [comment]
Thanks Witek!  In `modules/installation-and-upgrade/pages/ports.adoc`, we already list port 9100.  I'm wondering whether we should now add 9800, and if yes, how?

**Comment by witekest** [comment]
In fact, even more ports were missing in the server part. I've updated the table.

**Comment by keichwa** [comment]
> In fact, even more ports were missing in the server part. I've updated the table.

Thank you for spotting and fixing!

**Review by keichwa — APPROVED** [review]

**Comment by keichwa** [comment]
If nobody vetoes, I'll merge it today in the afternoon (CEST).

**Pull request merged**
