### PR TITLE
Postgresql14

### PR DESCRIPTION
**Pull request by mcalmer**
# Description

SUMA 4.3 will require postgresql 14 .

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Only merge when https://github.com/uyuni-project/uyuni/pull/4509 is merged

### CODE REVIEW

**Comment by mcalmer** [comment]
@0rnela @keichwa - please double check Uyuni. Uyuni did not change the DB version yet. This will happen next summer. This change apply only to SUMA 4.3 (Alpha/Beta/RC/GM)

**Review by keichwa — APPROVED** [review]
Note to ourselves: read the description (note!) before merging! ;-)

**Comment by keichwa** [comment]
https://github.com/uyuni-project/uyuni/pull/4509 now is merged.  I think we can merge this documentation PR, too.

**Comment by keichwa** [comment]
OTOH, we need master for uyuni... Dilemma...

**Comment by 0rnela** [comment]
Closing, the newer branch has been merged.

**Pull request closed without merging**
