### PR TITLE
Debian9 10 onboarding

### PR DESCRIPTION
**Pull request by gnuninu**
Created a new onboarding page for debian clients.

- uploaded pictures in assets/images and referenced them in the page
- Removed sections related with manual repo and channels creation of the debian tools - no longer required
- Pictures modified accordingly

### CODE REVIEW

**Comment by Loquacity** [comment]
Hi @gnuninu this is really good writing, thank you so much for putting it together! I would like to do an editing pass, mostly just to bring it into line with our standard writing style and practices. Possibly the best way to do that is to merge this PR, and then I'll do an editing pass in a new PR.

@keichwa @jcayouette what do you think?

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> @keichwa @jcayouette what do you think?

Sounds like a plan! :+1:  Thanks for working on this.

-- 
Karl Eichwalder                    SUSE Software Solutions Germany GmbH
Product & Solution Documentation   Maxfeldstraße 5
                                   90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by gnuninu** [comment]
Hi, Thanks @Loquacity !

We have added the debian tools repo and updated spacewalk-common-channels.ini accordingly so there will be no need to add this repo manually as described in this page. Shall we wait and update this PR before ? otherwise i can update this later on....

**Comment by Loquacity** [comment]
> Hi, Thanks @Loquacity !
> 
> We have added the debian tools repo and updated spacewalk-common-channels.ini accordingly so there will be no need to add this repo manually as described in this page. Shall we wait and update this PR before ? otherwise i can update this later on....

Yes, OK, let's update this PR so it's technically accurate first :)

**Comment by gnuninu** [comment]
Done, updated the page should be ok now :)

**Comment by Loquacity** [comment]
@gnuninu please review https://github.com/uyuni-project/uyuni-docs/pull/119

**Pull request merged**
