### PR TITLE
move client upgrade from Upgrade Guide to Client Config Guide.

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Short summary of why you created this PR

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [ ] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12544

### CODE REVIEW

**Comment by Loquacity** [comment]
Good call :+1:

**Comment by keichwa** [comment]
Thanks!  Everything is moved now.  I'd like to merge it.  Walk-thru and adjustments then can follow next week.  I probably should add a changelog entry.

**Review by jcayouette — APPROVED** [review]
Thank you, looks good!

**Review by Loquacity — APPROVED** [review]

**Comment by Loquacity** [comment]
> Thanks! Everything is moved now. I'd like to merge it. Walk-thru and adjustments then can follow next week. I probably should add a changelog entry.

Yes, changelog please!

**Pull request merged**
