### PR TITLE
minion is down (#670)

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Short summary of why you created this PR

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [x] Manager-4.1
- [ ] Manager-4.2
- [ ] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by Loquacity** [comment]
@jcayouette you'll notice this is going to the MU 4.1.3 branch, not manager-4.1. The manager-4.1 branch is completely unusable for me, crazy numbers of conflicts :confused:

**Comment by jcayouette** [comment]
> @jcayouette you'll notice this is going to the MU 4.1.3 branch, not manager-4.1. The manager-4.1 branch is completely unusable for me, crazy numbers of conflicts

Remember we rebuilt the manager-4.1 branch from master. I think if you rebase the conflicts will disappear.

**Comment by Loquacity** [comment]
> > @jcayouette you'll notice this is going to the MU 4.1.3 branch, not manager-4.1. The manager-4.1 branch is completely unusable for me, crazy numbers of conflicts
> 
> Remember we rebuilt the manager-4.1 branch from master. I think if you rebase the conflicts will disappear. I would not place this in manager-4.1.3 because we should be basing our MU on manager-4.1. I guess your local copy was out of date.

OK, i'll give this another try.

**Comment by Loquacity** [comment]
OK, I've reset my local copy of `manager-4.1`, so it's up to date now and I can access it properly again.

**Pull request closed without merging**
