### PR TITLE
Add Amazon Linux 2 in Client Configuration Guide (bsc#1186297)

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Add Amazon Linux 2 in Client Configuration Guide (bsc#1186297)

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/14981

### CODE REVIEW

**Review by juliogonzalez — APPROVED** [review]
I guess this is OK, but... render it and check if the menu shows what you expect. And remember to check the support matrix as well, just in case.

**Comment by keichwa** [comment]
I finally was able to build https://w3.suse.de/~ke/susemanager-4.2/suse_manager_client-configuration_guide.pdf .  Support matrix looks good to me, but I do not know which features are actually supported and which are not.

**Comment by juliogonzalez** [comment]
Support Matrix should be OK, as it was reviewed for another PR, and Pau provided feedback.

However I don't see Amazon Linux at `Table 1. Supported Client Systems`, and in fact... Debian is missing as well! Didn't we fix that with a separate PR :-?

**Comment by juliogonzalez** [comment]
> Support Matrix should be OK, as it was reviewed for another PR, and Pau provided feedback.
> 
> However I don't see Amazon Linux at `Table 1. Supported Client Systems`, and in fact... Debian is missing as well! Didn't we fix that with a separate PR :-?

Maybe the Debian part was fixed for 4.1 only? That problem is reported at the mailing list.

**Comment by juliogonzalez** [comment]
> Maybe the Debian part was fixed for 4.1 only? That problem is reported at the mailing list.

I reopened https://github.com/uyuni-project/uyuni-docs/issues/848

**Comment by keichwa** [comment]
Julio González Gil ***@***.***> writes:

> Support Matrix should be OK, as it was reviewed for another PR, and
> Pau provided feedback.
>
> However I don't see Amazon Linux at `Table 1. Supported Client
> Systems`, and in fact...

I now add:

| {amazon} 2
| {x86_64}
| {cross}
| {check}


> Debian is missing as well! Didn't we fix that with a separate PR :-?

For Debian, I'll create a separate card.

-- 
Karl Eichwalder

**Pull request merged**
