### PR TITLE
Do not assume the same list of books for Uyuni and SUSE Manager

### PR DESCRIPTION
**Pull request by mbussolotto**
# Description

Currently the build script assume that Uyuni and SUSE Manager has the same list of book. With this PR, we moved the books configuration to the product section

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

fix https://github.com/SUSE/spacewalk/issues/15928

### CODE REVIEW

**Comment by mbussolotto** [comment]
@jcayouette and @juliogonzalez briefly tested and seems that is working fine, can you please verify it? Thanks

**Comment by mbussolotto** [comment]
find some issue, recovert to draft

**Comment by mbussolotto** [comment]
ok, now it should be fine

**Comment by jcayouette** [comment]
Ill test first thing in the morning. Thanks @mbussolotto

**Comment by mbussolotto** [comment]
as agree with Joseph, also `antora.yml` shoudl be created at compile time

**Pull request merged**
