### PR TITLE
[WIP] New single t-shooting guide

### PR DESCRIPTION
**Pull request by 0rnela**
# Description

Tidying up of our troubleshooting guides. Currently they are in 3 separate books and are not created or organised in teh same way.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/17225

### CODE REVIEW

**Review by jcayouette — CHANGES_REQUESTED** [review]
Do not merge this prior to beta3 please. There are too many changes. I think for such large refactors we should plan in advance. This can create large catastrophes prior to our releases going out. Excellent work but we def need to add this to an MU.

**Comment by 0rnela** [comment]
@jcayouette - returning to WIP

**Comment by keichwa** [comment]
I'm also not that sure whether such a big structure change is a good thing after beta3.  I'd postpone it even longer.

**Comment by 0rnela** [comment]
Reworked post GM, as part of https://github.com/SUSE/spacewalk/issues/17225.

Closing this PR.

**Pull request closed without merging**
