### PR TITLE
 backport42 registration of SLE 12 clients (#1505)

### PR DESCRIPTION
**Pull request by keichwa**
# Description

https://github.com/SUSE/spacewalk/issues/14610

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by jcayouette — APPROVED** [review]

**Review by 0rnela — APPROVED** [review]

**Review by juliogonzalez — APPROVED** [review]
Ok, but remember SP3 and SP4 are still maintained: https://www.suse.com/lifecycle/

So you shoud add tme.

Same for SLE15 (SP0).

**Comment by keichwa** [comment]
> Ok, but remember SP3 and SP4 are still maintained: https://www.suse.com/lifecycle/
> So you shoud add them.
> Same for SLE15 (SP0).

Ok, will do.  But in this case I probably misunderstood you yesterday: https://github.com/uyuni-project/uyuni-docs/pull/1505#issuecomment-1089981379

**Comment by juliogonzalez** [comment]
> > Ok, but remember SP3 and SP4 are still maintained: https://www.suse.com/lifecycle/
> > So you shoud add them.
> > Same for SLE15 (SP0).
> 
> Ok, will do. But in this case I probably misunderstood you yesterday: [#1505 (comment)](https://github.com/uyuni-project/uyuni-docs/pull/1505#issuecomment-1089981379)

No, you are right. For some reason I understood this PR was changing the matrix.

So here you can do what I suggested at the comment yesterday.

Sorry about the confusion.

**Comment by keichwa** [comment]
Ok, thanks.  Then I'll merge this now.  If more is wanted or needed we better create a separate issue and PR.

**Pull request merged**
