### PR TITLE
remove unused file

### PR DESCRIPTION
**Pull request by keichwa**
# Description

https://github.com/uyuni-project/uyuni-docs/pull/1711

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by 0rnela — CHANGES_REQUESTED** [review]
This is part of the framework for the future single Tshooting guide. Please do not remove.

**Comment by keichwa** [comment]
> This is part of the framework for the future single Tshooting guide. Please do not remove.

We'd better stop merging half-done framework change into master.  I think "unused files" will be packaged and published and thus potentially can ruin the search.  I know it is cumbersome to keep those changes in a feature branch for a longer time.

@jcayouette how shall we proceed in this case?

**Comment by 0rnela** [comment]
> 
@keichwa 

I agree. But please keep in mind that the first attempt to merge all Tshooting guides into one was rejected because it was one massive change in a single PR (files were moved around, some were renamed, some consequently deleted).

**Review by jcayouette — APPROVED** [review]

**Review by jcayouette — CHANGES_REQUESTED** [review]
Lets leave as is for now then since it will be included in an upcoming PR

**Comment by keichwa** [comment]
@0rnela can you please re-check this one, and find a solution.  If the PR does not look useful, we can close it (IMO).

**Review by jcayouette — APPROVED** [review]

**Comment by keichwa** [comment]
PR is superfluous by now.

**Pull request closed without merging**
