### PR TITLE
Parametrize makefile

### PR DESCRIPTION
**Pull request by mbussolotto**
# Description

Parametrize makefile in order to have:
- less code  ( - 1600 lines)
- an easy way to add languages (just add few parameters)
- an easy way to add book (just one parameter)

More optimization can be done (in particular suma code and uuyuni code is still duplicated).

**Before running any `make` command, please remember to run `./configure`**

Tests here: https://github.com/mbussolotto/uyuni-docs/actions?query=branch%3Amaster

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by jcayouette** [comment]
Now this is looking good, awesome work Michele!

**Review by jcayouette — APPROVED** [review]
Of course Ill need to test, but this looks awesome. Nice work! Can this be backported to **manager-4.2**?

**Comment by mbussolotto** [comment]
> Of course Ill need to test, but this looks awesome. Nice work! Can this be backported to **manager-4.2**?
Yes, there's should no problem to backport it in manager-4.2. Let me see if I found a way to avoid `./configure` . I will let you know asap

**Comment by mbussolotto** [comment]
Hi @jcayouette , just add targets that includes configure. Now with `make all-suma` (or `make all-uyuni` ) you run `./configure` script and generate all the documentation. For the other target is more complicated, because they not exist before running `./configure`  (a classic chicken and egg problem :) ).
Hope this helps!

**Pull request merged**
