### PR TITLE
minor edits for clarity, fix xref

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

Just a quick review of the client upgrade stuff. Looks like a lot of it has been cleaned up since 4.1.2 was published, but I found a few other things, updated the xref in the Ref Guide, and moved some content that was already flagged.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/uyuni-project/uyuni-docs/issues/592

### CODE REVIEW

**Comment by Loquacity** [comment]
@keichwa As an aside, I know why you moved the client upgrade stuff to the Client Cfg, but I'm still not convinced it's the best place for it.

**Review by jcayouette — APPROVED** [review]

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> @keichwa As an aside, I know why you moved the client upgrade stuff to
> the Client Cfg, but I'm still not convinced it's the best place for
> it.

I've no strong preference where this actually might belong to.  We
must probably talk to Pau ;)  But we must keep in mind that clients are
not part of the {product}.

Last time I checked other OS vendors treat OS upgrades as an
installation.  I admit I did not re-check recently.

-- 
Karl Eichwalder

**Review by keichwa — APPROVED** [review]
nice work!

**Comment by Loquacity** [comment]
> Lana Brindley <notifications@github.com> writes:
> @keichwa As an aside, I know why you moved the client upgrade stuff to the Client Cfg, but I'm still not convinced it's the best place for it.
> I've no strong preference where this actually might belong to. We must probably talk to Pau ;) But we must keep in mind that clients are not part of the {product}. Last time I checked other OS vendors treat OS upgrades as an installation. I admit I did not re-check recently.

I already know Pau wants it in the Client Cfg, so I'm going to assume I've lost this argument already :wink:

**Pull request merged**
