### PR TITLE
gh-pages uyuni 2023.12 update

### PR DESCRIPTION
**Pull request by jcayouette**
*Before you submit this PR make sure you have added an entry to **.changelog** file.*

# Description

Uyuni-2023.12 release

No new content for the Report DB schema.

# Target branches

* Which documentation version does this PR apply to?
* Does this content need to be backported? If this is the case, create an issue for tracking it and add the link to this PR.
* Whenever possible, cross-reference each backport PR here, so that all backports can be easily accessed from the description.

- [x] gh-pages

# Links
- This PR tracks issue #<insert spacewalk issue, if any>
- Related development PR #<insert PR link, if any>

### CODE REVIEW

**Review by keichwa — APPROVED** [review]

**Comment by nodeg** [comment]
I am missing `openSUSE` under the supported clients and features.
image

**Comment by nodeg** [comment]
SUSE Liberty Linux is also missing in the left navigation
image
image

**Comment by keichwa** [comment]
> I am missing `openSUSE` under the supported clients and features. image
> 
> Ok, it seems that openSUSE is found below `SLES Supported Features`, which I found very confusing since we have a dedicated section for Leap Micro. image
> 
> It would make more sense the way we structure it in the client registration section and group SLES (SLES, SLE Micro) and openSUSE (Leap and Leap Micro): image

I think this is the related PR: https://github.com/uyuni-project/uyuni-docs/pull/2694

**Comment by keichwa** [comment]
> SUSE Liberty Linux is also missing in the left navigation image image

AFAIK, SLL is not supported with uyuni.  I'm not sure how this file slipped in (is it linked from somewhere else?).

**Comment by nodeg** [comment]
No, it is not linked. I just searched for `Liberty`.

**Pull request merged**
