### PR TITLE
Document openSUSE Leap 15.3

### PR DESCRIPTION
**Pull request by juliogonzalez**
# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2 (prepare the backport!)
- [x] Manager-4.1 (prepare the backport!)
- [ ] Manager-4.0

# Links

None, detected when I prepared something else for Uyuni.

### CODE REVIEW

**Comment by juliogonzalez** [comment]
[uyuni_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/6669299/uyuni_client-configuration_guide.pdf)
[suse_manager_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/6669313/suse_manager_client-configuration_guide.pdf)

**Review by jcayouette — COMMENTED** [review]
LGTM. Thanks!

**Comment by juliogonzalez** [comment]
Sorry, I don't know what I was doing and merged the PR by mistake. Let me know if you want a rollback :\

**Review by keichwa — COMMENTED** [review]
looks good, we can keep it.  we can ad more info to the changelog entry:
> as a supported client in the Client Configuration Guide.

**Pull request merged**
