### PR TITLE
Uyuni Server upgrade cleanup

### PR DESCRIPTION
**Pull request by keichwa**
# Description

https://github.com/SUSE/spacewalk/issues/16856

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by 0rnela** [comment]
@keichwa -- I have added @jcayouette as reviewer as well. From my past experiences, any changes with file names may cause some issues with translations. Please check with him before you merge this request.

**Comment by 0rnela** [comment]
Also, should this go to manager-4.3 branch too?

**Review by jcayouette — APPROVED** [review]

**Comment by keichwa** [comment]
> Also, should this go to manager-4.3 branch too?

No, not needed, IMO.  It affects uyuni only.

**Comment by keichwa** [comment]
> @keichwa -- I have added @jcayouette as reviewer as well. From my past experiences, any changes with file names may cause some issues with translations. Please check with him before you merge this request.

Yes, thanks for the reminder.  I'll create a separate PR for the filename change.

**Pull request merged**
