### PR TITLE
change 4.1 version info and related products

### PR DESCRIPTION
**Pull request by keichwa**
walk thru the Installation Guide.
documentation.suse.com links to be updated later.

close https://github.com/SUSE/spacewalk/issues/10774

### CODE REVIEW

**Comment by Loquacity** [comment]
See also: https://github.com/SUSE/spacewalk/issues/10921

**Comment by keichwa** [comment]
Questions:

- should I already change the SLE 15 SP1 links to SP2: https://documentation.suse.com/sles/15-SP2

**Comment by Loquacity** [comment]
> Questions:
> 
> * should I already change the SLE 15 SP1 links to SP2: https://documentation.suse.com/sles/15-SP2

Is it out yet?

**Comment by keichwa** [comment]
On 2020-03-20 01:03, Lana Brindley wrote:

>> * should I already change the SLE 15 SP1 links to SP2: 
>> https://documentation.suse.com/sles/15-SP2
> 
> Is it out yet?

no, okay I'll wait with updating the documentation.suse.com links.

-- 
Karl Eichwalder

**Pull request merged**
