### PR TITLE
pub clould overwriting

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Mention cloud images explicitly.  Those users must take action.
According to feedback by Stephen.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by keichwa** [comment]
@0rnela @jcayouette, reviews please ;) [this was proposed by the PC solution architect]

**Review by jcayouette — CHANGES_REQUESTED** [review]
Last sentence: ", you need to do some additional configuration to prevent them..."

**Comment by keichwa** [comment]
> Last sentence: ", you need to do some additional configuration to prevent them..."

Can you propose how to say this in a better way?  This phrase was already in before I applied Stephen's change request.

**Review by jcayouette — APPROVED** [review]

**Comment by keichwa** [comment]
Thanks Joseph, now I see--I was blinded by words...

**Pull request merged**
