### PR TITLE
Fix chinese translation for chinese language selector

### PR DESCRIPTION
**Pull request by cbosdo**
# Description

Replace the chinese translation for `Chinese` from 中国人 (chinese citizen)  to 中文 (chinese written language).

# Target branches

Which documentation version does this PR apply to?

- [X] Master (Default)
- [X] Manager-4.3
- [X] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by jcayouette** [comment]
Thank you :)

**Comment by cbosdo** [comment]
> Thank you :)

没关系！

**Review by keichwa — COMMENTED** [review]
LGTM technically, but we probably should involve Julia or Padraig when it comes to translation changes.  @PadraigDillon1 is this account name working for you?

**Comment by jcayouette** [comment]
Thank you @PadraigDillon1

**Comment by PadraigDillon1** [comment]
We have received the following feedback from our translators for this issue:

Chinese
The current translation isn’t correct. Below is the correct translation:
中文

Japanese
The translation for Japanese is correct. You can use “日本語”.
This may not be relevant, but the image of Japanese flag is little unusual.
The image of the Japanese flag is usually red circle with white background.
 

Korean
Yes, 한국어 is the correct translation for ‘Korean language’.
If possible, please update the translation below for improvement. 

1)
Source: Search the docs
Target: 문서 검색

2)
Source: 
On this page
1.  What is Uyuni?
2. Available Documentation

Target: 
이 페이지에서 다룰 내용
1. Uyuni란? 
2. 사용 가능한 설명서

**Comment by cbosdo** [comment]
> We have received the following feedback from our translators for this issue:
> 
> Chinese The current translation isn’t correct. Below is the correct translation: 中文

Glad to see I had it right 😉

**Review by keichwa — APPROVED** [review]

**Comment by keichwa** [comment]
I'll backport it to 4.3 and 4.2.

**Pull request merged**
