### PR TITLE
SAP enablement fix for makefiles

### PR DESCRIPTION
**Pull request by jcayouette**
# Description

Enablement for the new SAP guide in our makefiles.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [X] Manager-4.1
- [X] Manager-4.2
- [X] Uyuni

# Links

Partial: https://github.com/SUSE/spacewalk/issues/10772

### CODE REVIEW

**Review by keichwa — APPROVED** [review]

**Review by paususe — CHANGES_REQUESTED** [review]
Please split this PR in at least two commits:
- One with the enablement of the SAP QuickStart Guide in English (i. e. original AsciiDoc files)
- Another one with the enablement of the QuickStart Guide in Spanish and Simplified Chinese, and the new .pot and .po files

**Comment by Loquacity** [comment]
I've got confirmation from @juliogonzalez that we are not publishing SAP in this release, so this PR can wait.

**Comment by Loquacity** [comment]
Looking at this, it might be best to revert this commit, then do a new one according to Pau's suggestion above.

**Comment by Loquacity** [comment]
I have blatantly copied this PR into a new one here for English: https://github.com/uyuni-project/uyuni-docs/pull/558
I have not done any other lang, mostly because this guide is under no threat of imminent translation.

**Pull request closed without merging**
