### PR TITLE
Fix search bar url

### PR DESCRIPTION
**Pull request by mbussolotto**
# Description

Fix link when clicking the logo on search bar

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by jcayouette** [comment]
Looks pretty good, is this a WIP or is it complete?

**Comment by mbussolotto** [comment]
This one is completed without any dependencies with other PR, so it can be merged. Thanks!

**Review by jcayouette — APPROVED** [review]

**Comment by mbussolotto** [comment]
Hi @jcayouette , I added also the fix for the search box, can you please have a look at it ? Thanks!

**Review by jcayouette — APPROVED** [review]
Looks good go ahead and merge Ill test shortly after!

**Pull request merged**
