### PR TITLE
updates for PDF Branding 2020

### PR DESCRIPTION
**Pull request by jcayouette**
Initial Changes to PDF Branding for 2020. 

Suggestions and comments welcome! Let's make em aesthetic!

I am especially interested in our block styles.
* Literal blocks [DONE]
* Lists blocks [DONE]
* Captions (procedure and block titles) [DONE]
* Heading styles [DONE]
* Code blocks [DONE]
* Admonitions [DONE]

## Title Page
cover-page-2020

## TOC
TOC

## Procedures
Procedure_2020

## Image Border Styles
image-border-style

### CODE REVIEW

**Comment by Loquacity** [comment]
Definitely like the border styles and the red procedure headings, nice work! I'm not entirely comfortable with the green-on-black highlighting, I think it could be hard to read (especially if people are printing PDFs or in a high-contrast setting). I think we can probably dial down the code highlighting significantly, maybe make it the same size and colour as the main font, but monospaced?

**Comment by jcayouette** [comment]
@Loquacity, I agree. Trying to find a balance between legibility and something that pops out is difficult :) I will try and tone down the code blocks, they def do stand out a little too much! Also I did not take accessibility into account, green/red colorblindness here could be an issue :)

**Comment by Loquacity** [comment]
@jcayouette what's the ETA on the new branding?

**Comment by jcayouette** [comment]
@Loquacity I should be finished this week.

**Comment by jcayouette** [comment]
@paususe @Loquacity @keichwa Thoughts on update? If this is acceptable I would add a label for merging when the **webui** and **d.s.c** branding is done.

**Comment by Loquacity** [comment]
> @paususe @Loquacity @keichwa Thoughts on update? If this is acceptable I would add a label for merging when the **webui** and **d.s.c** branding is done.

can you update the screenshots?

**Comment by paususe** [comment]
> @paususe @Loquacity @keichwa Thoughts on update? If this is acceptable I would add a label for merging when the **webui** and **d.s.c** branding is done.

I'm not so sure abut the gray background in the PDF, it's not eco-friendly if someone wants to print it.

BTW I tried to build the docs from that branch to try to change that to white background and see how it looks but I didn't get the new branding :-?

**Comment by jcayouette** [comment]
Fixed white background in master branch after merge. :grinning:

**Pull request merged**
