### PR TITLE
relax region requirement for payg connect feature, add ds_store to gitignore

### PR DESCRIPTION
**Pull request by jamesongithub**
# Description
Relax region requirement for payg "feature". Same region isn't strictly necessary for payg feature.

# Target branches
master

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3
- [x] Manager-4.2 (>= 4.2.5)

# Links
Tested with SUMA in westus2, client in westus3.

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by keichwa — APPROVED** [review]
thank you!

**Comment by keichwa** [comment]
If possible, can you please add an entry to the top-level `.changelog` file?

**Comment by jamesongithub** [comment]
update. thanks~

**Comment by jamesongithub** [comment]
is there another step to actually deploy this? noticed the suma docs are not updated with this yet.

**Pull request merged**
