### PR TITLE
Documentation for Uyuni configuration Salt states

### PR DESCRIPTION
**Pull request by rjmateus**
Signed-off-by: Ricardo Mateus <rmateus@suse.com>

# Description

Part of https://github.com/SUSE/spacewalk/issues/9876

Short summary of why you created this PR

Feature in technical preview. 
Set of salt states which allow users to configure a server with organizations, user and system groups.

Initial commit doesn't add it to the docs menu so it can be decided by docs team the best place to put it.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.1
- [ ] Manager-4.2
- [ X ] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by rjmateus** [comment]
CC @moio @Loquacity

**Comment by rjmateus** [comment]
I added one file with execution modules and another with state modules

**Comment by Loquacity** [comment]
Let me know when you're ready with the draft, and I'll do an editing pass for you.

**Comment by moio** [comment]
I needed to add some commits and @rjmateus is off this week, so I am closing this PR and continuing on #523

**Pull request closed without merging**
