### PR TITLE
Add note about openscap security profile support

### PR DESCRIPTION
**Pull request by admd**
# Description
The SUSE security team has decided to not support all the profiles that come with scap-security-guide package. We need to add notes about it in our docs.

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by keichwa — APPROVED** [review]
Thanks for the PR, Abid!  Contents is fine, but before merging I'd add more adoc decoration `;)`.

**Comment by keichwa** [comment]
> > Thanks for the PR, Abid! Contents is fine, but before merging I'd add more adoc decoration `;)`.
> 
> Thank you for taking a look @keichwa . What adoc decoration should I add ? :).

Thanks, but do not worry.  I actually meant that I'll do this adoc dance ;)

**Comment by admd** [comment]
Thank you @keichwa for taking care of it, we will need to backport it to 4.2 docs as well.

**Comment by keichwa** [comment]
Abid Mehmood ***@***.***> writes:

> Thank you @keichwa for taking care of it, we will need to backport it
> to 4.2 docs as well.

Yes, thanks for the reminder.  I'll do this!

-- 
Karl Eichwalder

SUSE Software Solutions Germany GmbH, Geschäftsführer: Ivo Totev
HRB 36809, AG Nürnberg  Maxfeldstr. 5,  D-90409 Nürnberg

**Pull request merged**
