### PR TITLE
Add Debian 12 to documentation

### LINKED ISSUE #2353: Add Debian 12
Add Debian 12 to match https://github.com/uyuni-project/uyuni/pull/7255

### PR DESCRIPTION
**Pull request by mayrstefan**
# Description

Add Debian 12 to documentation

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3 https://github.com/uyuni-project/uyuni-docs/pull/2489

# Links

Fixes #2353

### CODE REVIEW

**Review by keichwa — APPROVED** [review]

**Comment by 0rnela** [comment]
@keichwa - before merging we need to update two more documents (this is why I created the checklist for adding/removing new clients a few weeks ago)

**Review by 0rnela — CHANGES_REQUESTED** [review]
We do not use modules/snippets/pages. Instead, the changes need to go to: modules/installation-and-upgrade/pages/client-requirements.adoc and
modules/client-configuration/pages/supported-features.adoc

**Comment by mayrstefan** [comment]
Maybe https://github.com/uyuni-project/uyuni/pull/7255 should be reviewed and merged before the docs get updated

**Review by keichwa — APPROVED** [review]
I added the "feature not ready" label, though. Please remove it or remind us when related code PR is merged.

**Review by jcayouette — APPROVED** [review]

**Review by 0rnela — APPROVED** [review]

**Comment by 0rnela** [comment]
Required for manager-4.3 too.

**Pull request merged**
