### PR TITLE
Debian 9 & 10 on SUMA

### PR DESCRIPTION
**Pull request by Loquacity**
~**_DO NOT MERGE DOCS REPO IS FROZEN_**~

~**_DO NOT MERGE UNTIL FEATURE IS MERGED_**~

# Description

Removes ifeval from the Debian chapter in the nav, and sets up the Debian chapter to include SUMA content.

~Still TODO: Find out the product names.~

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12500
Feature: https://github.com/SUSE/spacewalk/issues/12497 and https://github.com/SUSE/spacewalk/issues/12498

### CODE REVIEW

**Comment by Loquacity** [comment]
@juliogonzalez do you know what the product/channel names are? (they're not in refhead afaict).

**Review by keichwa — APPROVED** [review]

**Review by jcayouette — APPROVED** [review]
Looks good thanks!

**Comment by mcalmer** [comment]
@Loquacity Debian is now available on refhead server.

**Comment by Loquacity** [comment]
image
image

**Comment by mcalmer** [comment]
The "beta tools channel" is only available and visible for beta test customers. Normal customers do not  have it

**Comment by Loquacity** [comment]
> The "beta tools channel" is only available and visible for beta test customers. Normal customers do not have it

Yeah, I didn't add the beta one in, just the other (non-beta) one.

**Comment by Loquacity** [comment]
- [ ] Backport to 4.1: https://github.com/uyuni-project/uyuni-docs/pull/729

**Pull request merged**
