### PR TITLE
update documentation with activation key reference

### PR DESCRIPTION
**Pull request by rjmateus**
update documentation with activation key reference

# Description

Update documentation about the configuration salt states to include also activation keys

# Target branches

Which product version does this PR apply to?

- [x] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12495

### CODE REVIEW

**Comment by rjmateus** [comment]
cc @moio @Loquacity

**Review by Loquacity — APPROVED** [review]

**Review by moio — APPROVED** [review]

**Review by keichwa — APPROVED** [review]

**Review by jcayouette — APPROVED** [review]

**Comment by jcayouette** [comment]
Easiest review ever :)

**Comment by moio** [comment]
Please remember to :cherries: :pick: into 4.1!

:sweat_smile:

**Comment by Loquacity** [comment]
> Please remember to   into 4.1!

While I deeply admire your commitment to emoji, there's no need to cherry pick this. 4.1.3 will be built from master, and this is in master, so it will get there.

**Comment by moio** [comment]
:open_mouth:

:ok_hand:

:man_facepalming:

**Pull request merged**
