### PR TITLE
2023.04 uyuni gh-pages

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Part of https://github.com/SUSE/spacewalk/issues/21135 (gh-pages)

# Target branches

Which documentation version does this PR apply to?

- [ ] Master (Default)
- [ ] Manager-4.3
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by keichwa** [comment]
report DB will follow separately.

**Review by jcayouette — APPROVED** [review]
lgtm. Thanks!

**Comment by deneb-alpha** [comment]
@keichwa / @jcayouette I had a quick look but I need to admit that I didn't check all the changes made.

something I noticed is that there's at least one (probably more)  in `repo_metadata.html` the `edit this page` seems to still have links to your local machines
I tried to add a comment directly on the change but the browser is unresponsive.
~~~
<div class="edit-this-page"><a href="file:///home/docs/uyuni-docs//translations/en/modules/administration/pages/repo-metadata.adoc">Edit this Page</a></div>
~~~

**Comment by jcayouette** [comment]
Taking a look probably a wrong attribute.

**Review by deneb-alpha — APPROVED** [review]
ready to release

**Pull request merged**
