### PR TITLE
Fixing the unused file issue

### PR DESCRIPTION
**Pull request by 0rnela**
# Description

The building tool reports one unused file in our documentation. It is likely an old template that did not get worked on, i.e. does not provide any additional valuable content.

This PR investigates the actual cause and the decision of whether to remove the file permanently, or finally add it to the nav bar.

ETA: After checking it, I have removed the file, as it is unnecessary. It only contains copies of the existing config files delivered with the SUMA, with no additional explanations or information.

If we ever have a request for more detailed info, we can consider adding adequate and meaningful content, but my guess is that if we have lived this long without it properly included in the documentation, it was not necessary.  

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3 https://github.com/uyuni-project/uyuni-docs/pull/2115
- [x] Manager-4.2 https://github.com/uyuni-project/uyuni-docs/pull/2116

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by keichwa** [comment]
It looks as if there was an attempt in the past to remove it: https://github.com/uyuni-project/uyuni-docs/pull/1797

**Comment by 0rnela** [comment]
> It looks as if there was an attempt in the past to remove it: #1797

Indeed, and I have asked in the meantime if Joseph can do it. I don't recall why he didn't accept this before. In any case, the building tool is unnecessarily showing an error (one unused file) and we keep dragging this file from one version t another, while it has no use or value whatsoever.

I hope this is the end of the line for it.

**Review by keichwa — APPROVED** [review]

**Comment by 0rnela** [comment]
@jcayouette...

**Comment by jcayouette** [comment]
This should not be merged yet. Please check the feature_tests_uyuni action. It has failed. This is the reason it was not merged yet. I have not had time between my other tasks to solve the issue.

**Review by jcayouette — APPROVED** [review]

**Pull request merged**
