### PR TITLE
Revert "Update server-y-yast.adoc"

### PR DESCRIPTION
**Pull request by jcayouette**
Reverts uyuni-project/uyuni-docs#2159

### CODE REVIEW

**Comment by jcayouette** [comment]
@ptinley-vt I checked the adoc and noticed the lists did not have spaced between the concatenation `+`. This was probably causing your issue. I adjusted the adoc sources in *manager-4.2* so this probably should be solved.

**Comment by keichwa** [comment]
ok, but you removed the leading white space of the second line.  ok if you did this intentionally.

**Comment by jcayouette** [comment]
You can use the space prior to a new line or not. I prefer not too. But others prefer to use the spaces. 
```
* The document header in AsciiDoc is optional.
If present, it must start with a document title.

* Optional author and revision information lines
immediately follow the document title.

* The document header must be separated from
  the remainder of the document by one or more
  empty lines and it cannot contain empty lines.
  ```
  Either way the issue was list continuation.

**Comment by jcayouette** [comment]
Closing Patrick and I already fixed this.

**Pull request closed without merging**
