### PR TITLE
For wiz channel install, include only products

### PR DESCRIPTION
**Pull request by Loquacity**
# Description

For SUMA client install using the wizard, include only product names in the table, and remove the channel names. 

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [ ] Manager-4.1
- [x] Manager-4.2
- [x] Uyuni

# Links

Fixes https://github.com/SUSE/spacewalk/issues/12201

### CODE REVIEW

**Review by juliogonzalez — CHANGES_REQUESTED** [review]
If by "Product Name" you mean what the user see on the list of products, some of the product names in your lists are not right.

One quick example: you mention `centos6-x86_64` but the list has `CentOS 6 x86_64`, and all the other CentOS.

Please have a look at https://suma-refhead-srv.mgr.suse.de/rhn/manager/admin/setup/products and correct whatever needed, if there's something else :-)

**Comment by Loquacity** [comment]
heh, I was looking at the formatting, not the product names! :wink:

**Review by keichwa — APPROVED** [review]
Looks clean :)
Drive-by remark: iirc, we have a {webui} macro, but I'm not sure whether it will work in procedure titles ;)

**Comment by juliogonzalez** [comment]
Please provided renders if you want me to review. Otherwise it's hard to tell if there's something wrong in terms of format :-)

(Did I ever mention we should have this automated for each PR? :-D)

Product names look good, as far as I can tell.

**Comment by Loquacity** [comment]
> Looks clean :)
> Drive-by remark: iirc, we have a {webui} macro, but I'm not sure whether it will work in procedure titles ;)

From my experimenting, it will render the macros in titles, as long as they aren't the first word. Don't ask me why, though :woman_shrugging:

**Comment by Loquacity** [comment]
image
image
image
image
image
image
image
image
image

PDF: 
[suse_manager_client-configuration_guide.pdf](https://github.com/uyuni-project/uyuni-docs/files/5153301/suse_manager_client-configuration_guide.pdf)

**Comment by Loquacity** [comment]
Side-note: Absolutely loving the new HTML themes :heart_eyes:

**Review by jcayouette — APPROVED** [review]
Nice work looks good.

**Pull request merged**
