### PR TITLE
Add information about deprecated traditional clients

### PR DESCRIPTION
**Pull request by nodeg**
This will add some information regarding the deprecation of traditional clients in upcoming releases. Furthermore it adds some minimal steps in order to be able to register an unregistered traditional client as Salt minion afterwards.

I also remove some whitespaces from the changelog.

# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

I think this should apply to Manger 4.2, too but I am not sure.

# Links

### CODE REVIEW

**Review by keichwa — COMMENTED** [review]
For such an important documentation change, we need an issue on our project board first.  It would be good, if you'd split this PR (troubleshooting deleted client / deprecating traditional client).

**Comment by nodeg** [comment]
Hi @keichwa. Thanks for the reply. I can split up the PR into 2 separate ones. Can you take care of the card in the docs project board?

**Comment by nodeg** [comment]
I adjusted this PR and split out the troubleshooting guide to https://github.com/uyuni-project/uyuni-docs/pull/1421.

**Comment by keichwa** [comment]
> Hi @keichwa. Thanks for the reply. I can split up the PR into 2 separate ones. Can you take care of the card in the docs project board?

Yes, thanks for your help!  Here is the issue about status about trad. clients.

**Comment by nodeg** [comment]
Ok. If you have a proposition, just tell me, then I will add more commits.

**Comment by nodeg** [comment]
I did a rebase.

**Review by jcayouette — APPROVED** [review]

**Pull request merged**
