### PR TITLE
Add manual registration page to the navigation

### PR DESCRIPTION
**Pull request by paususe**
Fix manual registration page contents and add link to the navbar.

### CODE REVIEW

**Comment by paususe** [comment]
> We usually only capitalize server and proxy if they're expressed as `{productname} Server/Proxy`. In that formulation, it's a proper noun, so initcaps is appropriate. If it's just server/proxy on its own (without {productname}), then it's a noun, and no initcaps required. Other than that, I approve :)

Fixed

**Comment by paususe** [comment]
@Loquacity 
Thanks for approving but I don't have merge permissions :-(

**Comment by keichwa** [comment]
I do not like it too much that we use different styles for so-call replaceables: "SERVER.EXAMPLE.COM" vs. "<Activation_Key_Name>" vs. "<client>".  Then only one time we say the user should replace "<client>"...
Of course, we can address this later and I can merge you fix as-is.  Please decide :)

**Comment by paususe** [comment]
@keichwa 

If there is a recommended format for those, I can fix it now but you'll need to point me to the proper pattern.

Otherwise, please merge and let's decide on and use the same pattern in the future.

**Comment by keichwa** [comment]
> If there is a recommended format for those, I can fix it now but you'll need to point me to the proper pattern.
I think @Loquacity already tracked this as an issue or AI somewhere.
> Otherwise, please merge and let's decide on and use the same pattern in the future.
Thanks, I'll merge it now!

**Comment by Loquacity** [comment]
> @keichwa
> 
> If there is a recommended format for those, I can fix it now but you'll need to point me to the proper pattern.
> 
> Otherwise, please merge and let's decide on and use the same pattern in the future.

I asked on the SUSE Manager mailing list, and the accepted pattern was lowercase and angle brackets.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> I asked on the SUSE Manager mailing list, and the accepted pattern was
> lowercase and angle brackets.

Ok.  FYI, the documentation team promotes these "Documentation
Conventions" (find this section in almost all books):

https://documentation.suse.com/sles/15-SP1/html/SLES-all/preface-deployment.html#id-1.4.2.7

-- 
Karl Eichwalder                    SUSE Software Solutions Germany GmbH
Product & Solution Documentation   Maxfeldstraße 5
                                   90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by Loquacity** [comment]
> Lana Brindley <notifications@github.com> writes:
> I asked on the SUSE Manager mailing list, and the accepted pattern was lowercase and angle brackets.
> Ok. FYI, the documentation team promotes these "Documentation Conventions" (find this section in almost all books): https://documentation.suse.com/sles/15-SP1/html/SLES-all/preface-deployment.html#id-1.4.2.7

:woman_facepalming: I didn't realise there was a convention for this already.

For the record: I don't agree with putting it in the books directly, but I do think we should default to the docs team style where it makes sense to do so.

**Pull request merged**
