### PR TITLE
WIP: uyuni vs. suma, note about SLE 15 and python 3, and more

### PR DESCRIPTION
**Pull request by keichwa**
Mostly about bootstrapping and registration, uyuni and suma.

Do we want this in 4.0, too?  I think "yes":

- [x] 4.0
- [x] 4.1 (master)

### CODE REVIEW

**Comment by keichwa** [comment]
Julio González Gil <notifications@github.com> writes:

> Yes, I think the note about bootstrap scripts and python3 should
> stay. And I'd say even fur Uyuni, as we launched Uyuni on top of Leap
> 42.3 which was python2 based as well.

Ok, I changed it accordingly.  Thanks!

-- 
Karl Eichwalder            SUSE Software Solutions Germany GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by Loquacity** [comment]
> Do we want this in 4.0, too? I think "yes":
> 

I would beg to differ. These are just minor improvements to wording, so not worth the backport.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> I would beg to differ. These are just minor improvements to wording, so not worth the backport.

Yes, in general, you're right.  But at least partially, these are clear
bug fixes such as wrongly recommending to use Uyuni client tools in SUMA
context or saying the same thing twice that could confuse the reader (in
the procedure).  I agree it's a POV issue :)

-- 
Karl Eichwalder            SUSE Software Solutions Germany GmbH
PES / Documentation        Maxfeldstraße 5
                           90409 Nürnberg, Germany
Geschäftsführer: Felix Imendörffer (HRB 36809, AG Nürnberg)

**Comment by Loquacity** [comment]
Heh, fair point. I'll leave it up to you :stuck_out_tongue:

**Pull request merged**
