### PR TITLE
Retail Best Practices

### PR DESCRIPTION
**Pull request by nadvornik**
# Description

This add section about Retail Best Practices.
It documents the optimal way to handle the use case in https://github.com/SUSE/spacewalk/issues/21567

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.3 https://github.com/uyuni-project/uyuni-docs/pull/2393
- [ ] Manager-4.2

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Comment by 0rnela** [comment]
@nadvornik - can you please take a look at the conflict that needs resolving here?

**Comment by nadvornik** [comment]
OK, conflicts are fixed.
Now it needs review from @aaannz

**Review by aaannz — APPROVED** [review]
LGTM, one nitpicks, I think specifying XML-RPC API is not needed, we have JSON over HTTP as well which I think we will want to prefer in the future.

I also added active/inactive example to the contrib repo using JSON HTTP API (https://github.com/uyuni-project/contrib/pull/16)

**Review by 0rnela — CHANGES_REQUESTED** [review]
Please add .changelog to this PR.

**Review by 0rnela — APPROVED** [review]

**Pull request merged**
