### PR TITLE
de-duplicate usage of contact-methods-salt.adoc

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Stop including contact-methods-salt.adoc twice.  Use old contents in a new file named contact-methods-salt-cfgfile.adoc and start with a new Salt intro file (old filename).

I fear we also want this in 4.1.

# Target branches

Which product version does this PR apply to?

- [ ] Manager-4.0
- [x] Manager-4.1
- [x] Manager-4.2
- [ ] Uyuni

# Links

Fixes #<insert issue or PR link, if any>

move contents of the old file to the -cfgfile file, and
start adding Salt intro to the old file

### CODE REVIEW

**Comment by keichwa** [comment]
@Loquacity we included contact-methods-salt.adoc twice.  Can you help with a new general Salt intro text in the old file?

Maybe, it isn't clear what I try to do here ;)  If needed I can provide more info!

**Comment by Loquacity** [comment]
> @Loquacity we included contact-methods-salt.adoc twice. Can you help with a new general Salt intro text in the old file?
> 
> Maybe, it isn't clear what I try to do here ;) If needed I can provide more info!

Oh, really good spot! I see what you're trying to do. I'll checkout your branch and write some intro text for you.

**Comment by keichwa** [comment]
Lana Brindley <notifications@github.com> writes:

> Oh, really good spot! I see what you're trying to do. I'll checkout
> your branch and write some intro text for you.

Thank you, much appreciated!

-- 
Karl Eichwalder

**Review by jcayouette — APPROVED** [review]

**Review by Loquacity — APPROVED** [review]

**Comment by Loquacity** [comment]
@keichwa did you do the backport to 4.1?

**Pull request merged**
