### PR TITLE
Scap content #14009 keichwa

### PR DESCRIPTION
**Pull request by keichwa**
# Description

Short summary of why you created this PR

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Cosmetic changes before actually starting with https://github.com/SUSE/spacewalk/issues/14009

### CODE REVIEW

**Comment by Loquacity** [comment]
@keichwa I would recommend also writing this as a Cookbook recipe too. There are templates in the Cookbook folder in `master`.

**Comment by keichwa** [comment]
Lana Brindley ***@***.***> writes:

> @keichwa I would recommend also writing this as a Cookbook recipe
> too. There are templates in the Cookbook folder in `master`.

Probably a good idea!  I'll see what I can do.

-- 
Karl Eichwalder

**Comment by keichwa** [comment]
I'll probably create a fresh PR because of intermediate changes in master.

**Comment by keichwa** [comment]
superseded by https://github.com/uyuni-project/uyuni-docs/pull/1171

**Pull request closed without merging**
