### PR TITLE
Uyuni SUMA migration 0rnela

### PR DESCRIPTION
**Pull request by 0rnela**
# Description

This PR handles migration from 3.2 to 4.2. 

# Target branches

Which documentation version does this PR apply to?

- [x] Master (Default)
- [x] Manager-4.2
- [ ] Manager-4.1
- [ ] Manager-4.0

# Links

Fixes #<insert issue or PR link, if any>

### CODE REVIEW

**Review by paususe — CHANGES_REQUESTED** [review]
Some comments. I am building the docs to make sure I am not saying something stupid O:-)

**Comment by paususe** [comment]
> Some comments. I am building the docs to make sure I am not saying something stupid O:-)

Confirmed: I would simplify https://github.com/uyuni-project/uyuni-docs/blob/uyuni-sumamigration-0rnela/modules/upgrade/pages/server-x.adoc *a lot*, essentially removing *everything* specific and referring users to the 4.1 docs for 3.2 to 4.1 migration. In the 4.2 docs, just say "Migration from 3.2 to 4.2 is not directly supported, you need to go through 4.1 first. Check the 4.1 docs to migrate from 3.2 to 4.1 (https://documentation.suse.com/external-tree/en-us/suma/4.1/suse-manager/upgrade/server-x.html) and then check the 4.2 docs to migrate from 4.1 to 4.2".

Same for Proxy 3.2 to 4.1: just remove it from the 4.2 docs and refer users to the 4.1 docs, and when they are on 4.1, they can look into a minor 4.1 to 4.2 upgrade.
https://github.com/uyuni-project/uyuni-docs/blob/uyuni-sumamigration-0rnela/modules/upgrade/pages/proxy-x.adoc

**Comment by keichwa** [comment]
@0rnela is this now superseded by #963?  Maybe, next week we should check closely again.

**Comment by 0rnela** [comment]
Closing this PR. In the meantime we had a completely new script developed for DB migration which infers DB versions automatically, thus dropping the need to call the scripts related to specific versions.

Separate issue will be created to update uyuni documentation.

**Pull request closed without merging**
