### PR TITLE
43 - Removed Unified Installed from the Retail Guide

### PR DESCRIPTION
**Pull request by 0rnela**
Removed Unified Installed from the Retail Guide.

- [x] master https://github.com/uyuni-project/uyuni-docs/pull/3021
- [x]  manager 4.3

### CODE REVIEW

**Comment by aaannz** [comment]
You could before we moved to the VM image. But now only supported way is VM based install.

**Comment by aaannz** [comment]
But let's check with @admd if we should remove this in 4.3 branch as well, or keep it there even thou unsupported.

**Comment by admd** [comment]
@0rnela 
For 4.3, instead of removing it completely, please add a note on top that this is unsupported and only supported way is VM based install.

**Review by jcayouette — APPROVED** [review]

**Review by keichwa — CHANGES_REQUESTED** [review]
Hi Ornela, in the last days, Abid commented above.

**Comment by 0rnela** [comment]
Closing -see https://github.com/uyuni-project/uyuni-docs/pull/3100.

**Pull request closed without merging**
